[project]
name = "ebpfcat"
version = "0.0.1"
dependencies = []

[project.scripts]
ec-scanbus = "ebpfcat.scripts:scanbus"
ec-info = "ebpfcat.scripts:info"
ec-eeprom = "ebpfcat.scripts:eeprom"
ec-create-test = "ebpfcat.scripts:create_test"
